kotlin.code.style=official
# plugin
pluginGroup=com.wavesplatform
pluginName=rideplugin
pluginVersion=0.0.6
# Gradle Releases -> https://github.com/gradle/gradle/releases
gradleVersion = 8.6
# platform
platformType=IC
platformVersion=2024.2
platformPlugins=
# Supported build number ranges and IntelliJ Platform versions -> https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
pluginSinceBuild = 242
pluginUntilBuild = 243.*

# Opt-out flag for bundling Kotlin standard library -> https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library
# suppress inspection "UnusedProperty"
kotlin.stdlib.default.dependency = false
